### PR TITLE
Fix flexsearch option being overridden

### LINKED ISSUE #594: Search broken when deploying to Vercel
I don’t know if it’s Nextra, Vercel, or my issue. But somehow, search is built and works locally but not when deployed. I’m using [nextra@2.0.0-beta.10](https://github.com/shuding/nextra/releases/tag/nextra%402.0.0-beta.10) and newest nextra-theme-docs, but with modified fonts/colors.

Any hints on what could be wrong?

580BEFEB-FE10-41F2-9F27-E5E809BFAFAF
51E0032A-B359-44FA-A069-EBB650006F95

### PR DESCRIPTION
**Pull request by shuding**
Closes #594. I noticed that the flexsearch option being overridden here:

CleanShot 2022-08-01 at 14 37 33@2x

Which is not needed, we should just remove it.

### CODE REVIEW

File: packages/nextra-theme-docs/src/index.tsx [hunk 1]
```diff
@@ -282,8 +282,7 @@ const Content = ({
 const createLayout = (opts: PageOpts, config: DocsThemeConfig) => {
   const extendedConfig = {
     ...defaultConfig,
-    ...config,
-    unstable_flexsearch: opts.unstable_flexsearch
+    ...config
```
Comment (B2o5T) [inline packages/nextra-theme-docs/src/index.tsx:285]: we no longer provide `unstable_flexsearch` in theme config, but only in `withNextra`

Comment (B2o5T) [reply packages/nextra-theme-docs/src/index.tsx:285]: more info about this change https://github.com/shuding/nextra/pull/524#discussion_r927798692

**Review by B2o5T — CHANGES_REQUESTED** [review]
it's not overridden:
you have `unstable_flexsearch: false` in `nextraConfig`
you have `unstable_flexsearch: true` in theme, but we no longer take care of this value since we take value only from `nextraConfig`

**Comment by shuding** [comment]
Makes sense, I think it should be enabled automatically based on `nextraConfig`

**Comment by shuding** [comment]
OK I know what's the root cause now, under the condition `IS_PRODUCTION && indexContentEmitted.has(filename)` we are changing `unstable_flexsearch` to false to bypass re-indexing, but it affects the layout too.

**Comment by B2o5T** [comment]
Nice catch!
